name: flight-profile-clustering
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - openpyxl
  - tqdm
  - jupyter
  - ipykernel
  - pip
